static struct downloaderr _ftp_errlist[] = {
    { 110, DLERR_OK, "Restart marker reply" },
    { 120, DLERR_TEMP, "Service ready in a few minutes" },
    { 125, DLERR_OK, "Data connection already open; transfer starting" },
    { 150, DLERR_OK, "File status okay; about to open data connection" },
    { 200, DLERR_OK, "Command okay" },
    { 202, DLERR_PROTO, "Command not implemented, superfluous at this site" },
    { 211, DLERR_INFO, "System status, or system help reply" },
    { 212, DLERR_INFO, "Directory status" },
    { 213, DLERR_INFO, "File status" },
    { 214, DLERR_INFO, "Help message" },
    { 215, DLERR_INFO, "Set system type" },
    { 220, DLERR_OK, "Service ready for new user" },
    { 221, DLERR_OK, "Service closing control connection" },
    { 225, DLERR_OK, "Data connection open; no transfer in progress" },
    { 226, DLERR_OK, "Requested file action successful" },
    { 227, DLERR_OK, "Entering Passive Mode" },
    { 229, DLERR_OK, "Entering Extended Passive Mode" },
    { 230, DLERR_OK, "User logged in, proceed" },
    { 250, DLERR_OK, "Requested file action okay, completed" },
    { 257, DLERR_OK, "File/directory created" },
    { 331, DLERR_AUTH, "User name okay, need password" },
    { 332, DLERR_AUTH, "Need account for login" },
    { 350, DLERR_OK, "Requested file action pending further information" },
    { 421, DLERR_DOWN, "Service not available, closing control connection" },
    { 425, DLERR_NETWORK, "Can't open data connection" },
    { 426, DLERR_ABORT, "Connection closed; transfer aborted" },
    { 450, DLERR_UNAVAIL, "File unavailable (e.g., file busy)" },
    { 451, DLERR_SERVER, "Requested action aborted: local error in processing" },
    { 452, DLERR_FULL, "Insufficient storage space in system" },
    { 500, DLERR_PROTO, "Syntax error, command unrecognized" },
    { 501, DLERR_PROTO, "Syntax error in parameters or arguments" },
    { 502, DLERR_PROTO, "Command not implemented" },
    { 503, DLERR_PROTO, "Bad sequence of commands" },
    { 504, DLERR_PROTO, "Command not implemented for that parameter" },
    { 530, DLERR_AUTH, "Not logged in" },
    { 532, DLERR_AUTH, "Need account for storing files" },
    { 535, DLERR_PROTO, "Bug in MediaHawk Video Kernel FTP server" },
    { 550, DLERR_UNAVAIL, "File unavailable (e.g., file not found, no access)" },
    { 551, DLERR_PROTO, "Requested action aborted. Page type unknown" },
    { 552, DLERR_FULL, "Exceeded storage allocation" },
    { 553, DLERR_EXISTS, "File name not allowed" },
    { 999, DLERR_PROTO, "Protocol error" },
    { -1, DLERR_UNKNOWN, "Unknown FTP error" }
};
